[package]
name = "cavernos-cli"
version = "0.1.0"
authors = ["Jordan West <jordwest@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
